### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by greenSyntax** [Zeoh/e-phone#1]
I can't build your source. Can you suggest me how to do that? 
I'm assuming, I need to update with gossip submodule as Gossip directory is empty for now.

**Comment by zacw7** [comment]
Sorry, this repository is out of maintenance. It looks like gossip is out of maintenance too.
If you are looking for a SIP library, you could check [PJSIP](https://trac.pjsip.org/repos/wiki/Getting-Started/iPhone).
